# Generated by Django 2.0.13 on 2020-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSD_value', models.FloatField(blank=True, default=0)),
                ('Freq_value', models.FloatField(blank=True, default=0)),
                ('PSD_svg', models.FloatField(blank=True, default=0)),
                ('Freq_svg', models.FloatField(blank=True, default=0)),
                ('sc_tag', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
